name: yadp
main: com.github.peter200lx.yadp.YADP
version: 0.4
website: https://github.com/Peter200lx/yadp
author: peter200lx
description: >
             Yet Another Duplicator Plugin. This aims to create a block duplication feature that supports permissions and additional configuration.
commands:
  yadp:
    description: Holder command for reload and more
    usage: |
           /<command> [reload|tools]
           Example: /<command> - Prints help for plugin.
           Example: /<command> reload - Reloads settings from disk
           Example: /<command> tools - Lists tools available to player
permissions:
    yadp.*:
        description: Gives access to all permissions for yadp
        default: op
        children:
            yadp.reload: true
            yadp.tool.dupe: true
            yadp.tool.scroll: true
    yadp.reload:
        description: Allows the player to reload yadp from configuration file.
    yadp.tool.dupe:
        description: Allows the player to use the duplicator tool.
        default: true
    yadp.tool.scroll:
        description: Allows the player to use the data scrolling tool.
